### ISSUE TITLE
Link forwards to non Microsoft site

### ISSUE THREAD

**Issue by madmapper** [MicrosoftDocs/IIS.Administration-docs#33]
example link mentioned twice in this article forwards to:
https://msft-sme.myget.org/Account/Login?ReturnUrl=%2Ffeed%2FIndex%2Fwindows-admin-center-feed

Is MyGet the intended destination for this example?

**Comment by loaderladdy** [comment]
I think the problem lies on the iis.net website. The code here references the link, so there must be a redirect on the iis.net web server for “manage.iis.net” that points to the MyGet.org website.  Perhaps this is by design of the iis.net web server admins.

As @madmapper asks, should this document have a link to manage.iis.net or just reference manage.iis.net as an example of a CORS policy?

The wording of the document implies that all CORS policies **must** contain a link to manage.iss.net.  Is this true?

**Comment by loaderladdy** [comment]
@mairaw @jimmyca15 Hi guys, do you have any views on the issue that @madmapper and myself raised on this seemingly broken link.

I’ve exchanged emails with an iis.net admin and they said the redirect was via Microsoft. I can forward the email if you like. Let me know.

**Comment by mairaw** [comment]
Yes please do. My email is mairaw at microsoft dot com.

What is the article where this is showing up?

/cc @shirhatti

**Comment by shirhatti** [comment]
It was the intended link in the past. The docs need to updated to mention that the [Management Portal](https://docs.microsoft.com/en-us/iis-administration/management-portal/connecting) and `manage.iis.net` are no longer supported.
 
👀: @John-Hart

**Comment by loaderladdy** [comment]
Should it redirect to MyGet.org though?.

I've emailed iis.net web admin's reply to @mairaw

**Comment by mairaw** [comment]
The e-mail thread was with @terrimorton.

**Comment by klawrawkz** [comment]
The redirect is confusing. If the _"Management Portal and manage.iis.net are no longer supported"_, as @shirhatti states above, the links need to be removed (or replaced if there is some new sample out on the innerwebs).

**Comment by rDarge** [comment]
Why is this still happening? I'm getting redirected to https://msft-sme.myget.org/ when I click on the "Manage IIS" link on https://www.iis.net/?utm_medium=iis-deployment 

@mairaw @terrimorton
